packages:
  - 'buddy'
  - 'plugins/*'
  - 'packages/*'
  - 'components/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - 'packages/plugin-time-view'
  - 'packages/cosy'
  - 'packages/cosy-framework'
  - 'packages/cosy-logger'
  - 'packages/cosy-keyboard'
  - 'packages/vsc_extension' 