name: gitok
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.2.2

environment:
  sdk: '>=3.3.0 <4.0.0'

# 应用配置
config:
  auto_update:
    # main 分支存放稳定版本，pre 分支存放预发布版本，这样用户不会收到预发布版本的更新通知
    feed_url: https://raw.githubusercontent.com/CofficLab/GitOK/main/appcast.xml
    check_interval: 3600 # 每小时检查一次

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path: ^1.8.3
  file_picker: ^6.1.1
  flutter_colorpicker: ^1.0.3
  http: ^1.1.0
  flutter_json_viewer: ^1.0.1
  provider: ^6.0.0
  diff_match_patch: ^0.4.1
  reorderable_grid: ^1.0.10
  process: ^5.0.3
  git: ^2.3.1
  macos_window_utils: ^1.5.0
  cupertino_icons: ^1.0.8
  hotkey_manager: ^0.2.3
  bot_toast: ^4.1.3
  preference_list: ^0.0.2
  flutter_foreground_task: ^8.17.0
  window_manager: ^0.4.3
  tray_manager: ^0.3.2
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  archive: ^4.0.4
  auto_updater: ^0.2.0
  yaml: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/basic/
    - assets/app_icon.png
