name: gitok
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path: ^1.8.3
  file_picker: ^6.1.1
  flutter_colorpicker: ^1.0.3
  http: ^1.1.0
  flutter_json_viewer: ^1.0.1
  provider: ^6.0.0
  diff_match_patch: ^0.4.1
  reorderable_grid: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/basic/
