# GitOK 应用配置文件

# 窗口设置
window:
  # 是否显示窗口标题栏的红绿灯按钮
  showTrafficLights: false
  # 是否显示调试工具栏
  showDebugToolbar: true
  # 调试工具栏位置 (可选值: "right", "bottom", "left", "undocked")
  debugToolbarPosition: "bottom" 