# GitOK 应用配置文件

# 窗口设置
window:
  # 是否显示窗口标题栏的红绿灯按钮
  # 可选值: true (显示), false (隐藏)
  showTrafficLights: false
  # 是否显示调试工具栏
  # 可选值: true (显示), false (隐藏)
  showDebugToolbar: true
  # 调试工具栏位置
  # 可选值: "right", "bottom", "left", "undocked"
  debugToolbarPosition: 'bottom'
  # 是否启用类似Spotlight的模式
  # 可选值: true (启用), false (禁用)
  spotlightMode: true
  # Spotlight模式的全局快捷键
  # 格式: 辅助键 (Control, Command, Alt, Option, Shift) + 字母/数字/符号
  # 例如: 'CommandOrControl+Space', 'Alt+S', 'Command+Shift+P'
  spotlightHotkey: 'Option+Space'
  # Spotlight模式的窗口尺寸
  spotlightSize:
    # 窗口宽度 (像素)
    width: 700
    # 窗口高度 (像素)
    height: 1200
  # 窗口是否始终置顶
  # 可选值: true (置顶), false (普通层级)
  alwaysOnTop: true
  # 是否跟随当前桌面/工作区
  # 可选值: true (跟随), false (不跟随)
  # 启用后,在不同工作区按快捷键将在当前工作区显示
  followDesktop: true
