# GitOK 应用配置文件

# App管理器设置
app:
  # 是否启用App管理器的日志输出
  # 可选值: true (启用), false (禁用)
  enableLogging: false
  # 日志级别
  # 可选值: "debug", "info", "warn", "error"
  logLevel: 'info'

# 窗口设置
window:
  # 是否显示窗口标题栏的红绿灯按钮
  # 可选值: true (显示), false (隐藏)
  showTrafficLights: false
  # 是否显示调试工具栏
  # 可选值: true (显示), false (隐藏)
  showDebugToolbar: false
  # 调试工具栏位置
  # 可选值: "right", "bottom", "left", "undocked"
  debugToolbarPosition: 'bottom'
  # 是否启用类似Spotlight的模式
  # 可选值: true (启用), false (禁用)
  spotlightMode: true
  # Spotlight模式的全局快捷键
  # 格式: 辅助键 (Control, Command, Alt, Option, Shift) + 字母/数字/符号
  # 例如: 'CommandOrControl+Space', 'Alt+S', 'Command+Shift+P'
  spotlightHotkey: 'Option+Space'
  # Spotlight模式的窗口尺寸
  spotlightSize:
    # 窗口宽度 (像素)
    width: 700
    # 窗口高度 (像素)
    height: 800
  # 窗口是否始终置顶
  # 可选值: true (置顶), false (普通层级)
  alwaysOnTop: true
  # 是否跟随当前桌面/工作区
  # 可选值: true (跟随), false (不跟随)
  # 启用后,在不同工作区按快捷键将在当前工作区显示
  followDesktop: true
  # 是否启用窗口管理器的日志输出
  # 可选值: true (启用), false (禁用)
  enableLogging: false
  # 日志级别
  # 可选值: "debug", "info", "warn", "error"
  logLevel: 'info'

# 插件管理器设置
plugin:
  # 插件目录设置
  directories:
    # 内置插件目录
    # 相对于应用程序目录
    builtIn: 'resources/plugins'
    # 用户插件目录
    # 相对于用户数据目录
    # 在 macOS 上通常是 ~/Library/Application Support/buddy/plugins
    # 在 Windows 上通常是 %APPDATA%/buddy/plugins
    # 在 Linux 上通常是 ~/.config/buddy/plugins
    user: 'plugins'
    # 开发插件目录
    # 相对于用户数据目录，用于开发和测试插件
    dev: 'dev-plugins'
  # 是否启用插件管理器的日志输出
  # 可选值: true (启用), false (禁用)
  enableLogging: true
  # 日志级别
  # 可选值: "debug", "info", "warn", "error"
  logLevel: 'info'

# IPC管理器设置
ipc:
  # 是否启用IPC管理器的日志输出
  # 可选值: true (启用), false (禁用)
  enableLogging: true
  # 日志级别
  # 可选值: "debug", "info", "warn", "error"
  logLevel: 'info'

# Command键管理器设置
command:
  # 是否启用Command键管理器的日志输出
  # 可选值: true (启用), false (禁用)
  enableLogging: false
  # 日志级别
  # 可选值: "debug", "info", "warn", "error"
  logLevel: 'info'
