name: Pre Release

on:
  push:
    branches:
      - pre

permissions:
  contents: write

env:
  TAG: ${{ github.sha }}
  Identity: ''
  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
  NEW_VERSION: 'x.x.x'
  TEAM_ID: ''
  CERT_ID: ''
  ED_SIGNATURE: ''
  FILE_SIZE: ''
  DMG_FILENAME: ''
  VERSION: ''
  DMG_FILE: ''
  APP_PATH: ''

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 更新版本号
        run: |
          # 读取当前版本号
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //' | tr -d "'")
          # 分割版本号
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          # 增加补丁版本号
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          # 更新 pubspec.yaml 中的版本号
          sed -i '' "s/version: .*/version: $NEW_VERSION/" pubspec.yaml
          echo "TAG=$NEW_VERSION" >> $GITHUB_ENV
      - name: 打标签并推送到仓库
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🎨 Bump version to ${{ env.TAG }}'
          commit_user_name: GitHub Action
          tagging_message: ${{ env.TAG }}

  rebase:
    needs:
      - bump
    runs-on: ubuntu-latest
    steps:
      - name: 拉取 dev 分支
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: 拉取 pre 分支
        run: git fetch origin pre
      - name: Rebase dev on pre
        continue-on-error: true
        run: git rebase origin/pre
      - name: Push the rebased dev branch
        continue-on-error: true
        run: git push origin dev

  build_with_signing:
    needs:
      - bump
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: pre
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # https://docs.github.com/zh/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
      - name: Install the Apple certificate and provisioning profile
        env:
          P12_PASSWORD: ${{ secrets.BUILD_CERTIFICATE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_GITOK_MACOS }}
          KEYCHAIN_PASSWORD: 'xxx'
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "${{ env.BUILD_CERTIFICATE_BASE64 }}" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: 生成 App Store Connect API 的 AuthKey
        run: |
          mkdir -p ./private_keys
          echo -n "${{ secrets.APP_STORE_CONNECT_KEY_BASE64 }}" | base64 --decode -o ./private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8
      - name: Get Certificate Info
        run: |
          # 获取证书信息并解析
          CERT_INFO=$(security find-identity -v -p codesigning | grep '^[[:space:]]*1)' | head -n 1)
          CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
          TEAM_ID=$(echo "$CERT_INFO" | grep -o '[A-Z0-9]\{10\}' | tail -n 1)
          echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
          echo "TEAM_ID=$TEAM_ID" >> $GITHUB_ENV

      - name: Configure Xcode project
        run: |
          # 修改所有签名相关的配置
          PBXPROJ="macos/Runner.xcodeproj/project.pbxproj"

          # 替换所有 Mac Development 为实际的证书 ID
          sed -i '' "s/\"Mac Development\"/\"${{ env.CERT_ID }}\"/g" $PBXPROJ

          # 替换所有 DEVELOPMENT_TEAM
          sed -i '' "s/DEVELOPMENT_TEAM = \".*\"/DEVELOPMENT_TEAM = \"${{ env.TEAM_ID }}\"/g" $PBXPROJ

          # 设置手动签名
          sed -i '' 's/CODE_SIGN_STYLE = Automatic/CODE_SIGN_STYLE = Manual/g' $PBXPROJ

          # 设置 CODE_SIGN_IDENTITY
          sed -i '' "s/CODE_SIGN_IDENTITY = \".*\"/CODE_SIGN_IDENTITY = \"${{ env.CERT_ID }}\"/g" $PBXPROJ

          # 设置 Debug 和 Release 配置的签名身份
          sed -i '' "s/\"CODE_SIGN_IDENTITY[^\"]*\" = \".*\"/\"CODE_SIGN_IDENTITY[sdk=macosx*]\" = \"${{ env.CERT_ID }}\"/g" $PBXPROJ

          # 清除可能存在的配置文件指定器
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = ".*"/PROVISIONING_PROFILE_SPECIFIER = ""/g' $PBXPROJ

      - name: Build macOS App
        run: flutter build macos --release
      - name: find identity
        run: |
          i=$(security find-identity -v -p codesigning | grep '^[[:space:]]*1)' | awk -F'[(|)]' '{print $3}')
          echo "Identity=$i" >> $GITHUB_ENV

      - name: 获取应用程序路径和名称
        run: |
          APP_PATH=$(find build/macos/Build/Products/Release/ -type d -name "*.app" | head -n 1)
          APP_NAME=$(basename $APP_PATH)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

          echo "APP_PATH=$APP_PATH"
          echo "APP_NAME=$APP_NAME"

      # Codesign sparkle
      - name: Codesign sparkle
        run: |
          codesign -f -s ${{ env.Identity }} -o runtime ${{ env.APP_PATH }}/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Installer.xpc
          codesign -f -s ${{ env.Identity }} -o runtime --preserve-metadata=entitlements ${{ env.APP_PATH }}/Contents/Frameworks/Sparkle.framework/Versions/B/XPCServices/Downloader.xpc
          codesign -f -s ${{ env.Identity }} -o runtime ${{ env.APP_PATH }}/Contents/Frameworks/Sparkle.framework/Versions/B/Autoupdate
          codesign -f -s ${{ env.Identity }} -o runtime ${{ env.APP_PATH }}/Contents/Frameworks/Sparkle.framework/Versions/B/Updater.app
          codesign -f -s ${{ env.Identity }} -o runtime ${{ env.APP_PATH }}/Contents/Frameworks/Sparkle.framework

      # Codesign App
      - name: Codesign
        run: codesign --force -s ${{ env.Identity }} --option=runtime ${{ env.APP_PATH }}

      # Codesign Check
      - name: Codesign Check
        run: codesign -dv ${{ env.APP_PATH }}

      # Create DMG
      - name: Create DMG
        run: |
          # 安装 create-dmg
          npm i -g create-dmg

          # 创建 DMG
          create-dmg ${{ env.APP_PATH }}

          # 重命名 DMG 文件（移除空格）
          for file in *.dmg; do
            mv "$file" "${file// /-}"
          done

      - name: 确保脚本可执行
        run: chmod +x scripts/*.sh

      - name: 获取 DMG 文件信息
        run: |
          # 使用我们的 DMG 信息获取脚本
          DMG_INFO=$(./scripts/get_dmg_info.sh .)

          # 解析脚本输出并设置环境变量
          DMG_FILE=$(echo "$DMG_INFO" | grep "DMG_FILE=" | cut -d= -f2)
          DMG_FILENAME=$(echo "$DMG_INFO" | grep "DMG_FILENAME=" | cut -d= -f2)
          FILE_SIZE=$(echo "$DMG_INFO" | grep "FILE_SIZE=" | cut -d= -f2)

          # 设置 GitHub Actions 环境变量
          echo "DMG_FILE=$DMG_FILE" >> $GITHUB_ENV
          echo "DMG_FILENAME=$DMG_FILENAME" >> $GITHUB_ENV
          echo "FILE_SIZE=$FILE_SIZE" >> $GITHUB_ENV

          echo "DMG 文件信息："
          echo "路径: $DMG_FILE"
          echo "文件名: $DMG_FILENAME"
          echo "大小: $FILE_SIZE 字节"

      - name: Notary
        continue-on-error: true
        run: |
          file=${{ env.DMG_FILE }}
          xcrun notarytool submit "$file" \
            --key ./private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8 \
            --key-id=${{ secrets.APP_STORE_CONNECT_KEY_ID }} \
            --issuer ${{ secrets.APP_STORE_CONNECT_KEY_ISSER_ID }} \
            --wait \
            --timeout 10m
          stapler staple "$file"

          # 如果出现错误，查询日志
          # xcrun notarytool log f66d58e3-d03a-4202-937e-5fca4e7cea83 
          #   --key ./private_keys/AuthKey_${{ secrets.APP_STORE_CONNECT_KEY_ID }}.p8 \
          #   --key-id ${{ secrets.APP_STORE_CONNECT_KEY_ID }} \
          #   --issuer ${{ secrets.APP_STORE_CONNECT_KEY_ISSER_ID }}
      - name: 公证结果
        continue-on-error: true
        run: |
          file=${{ env.DMG_FILE }}
          stapler validate "$file"

      # 自动更新相关步骤
      - name: 使用脚本生成 Sparkle 签名
        run: |
          # 使用我们的签名脚本
          SIGNATURE_OUTPUT=$(echo "${{ secrets.SPARKLE_PRIVATE_KEY_GITOK }}" | ./scripts/sign_update.sh "${{ env.DMG_FILE }}")

          # 提取签名值
          ED_SIGNATURE=$(echo "$SIGNATURE_OUTPUT" | grep -o 'sparkle:edSignature="[^"]*"')
          echo "ED_SIGNATURE=$ED_SIGNATURE" >> $GITHUB_ENV

      - name: 使用脚本生成 appcast.xml
        run: |
          # 使用我们的 appcast 生成脚本
          ./scripts/generate_appcast.sh "${{ env.DMG_FILE }}" "${{ env.TAG }}" "${{ env.ED_SIGNATURE }}"

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          prerelease: true
          files: |
            ./**/*.dmg
            ./appcast.xml
