name: Publish Pre-release Buddy

on:
  push:
    branches:
      - electron

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install node-gyp
        run: npm install -g node-gyp

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install

      # - name: build-linux
      #   if: matrix.os == 'ubuntu-latest'
      #   run: cd buddy && pnpm run build:linux

      # macOS 构建和签名
      - name: Setup macOS signing
        id: signing
        if: matrix.os == 'macos-latest'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          BUILD_CERTIFICATE_P12_PASSWORD: ${{ secrets.BUILD_CERTIFICATE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64_GITOK_MACOS }}
          APP_STORE_CONNECT_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_KEY_BASE64 }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_KEY_ISSER_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ISSER_ID }}
        run: |
          chmod +x ./scripts/setup-macos-signing.sh
          source ./scripts/setup-macos-signing.sh
          echo "signing_identity=$SIGNING_IDENTITY" >> $GITHUB_OUTPUT
          echo "team_id=$TEAM_ID" >> $GITHUB_OUTPUT
          echo "pp_path=$PP_PATH" >> $GITHUB_OUTPUT

      - name: Update electron-builder config for CI
        if: matrix.os == 'macos-latest'
        env:
          PP_PATH: ${{ steps.signing.outputs.pp_path }}
        run: |
          # 使用 yq 工具修改 yaml 文件
          brew install yq
          cd buddy
          # 使用脚本设置的配置文件路径
          yq -i ".mac.provisioningProfile = \"$PP_PATH\"" electron-builder.yml
          yq -i '.mac.notarize = true' electron-builder.yml
          yq -i '.mac.identity = null' electron-builder.yml

      - name: build-mac
        if: matrix.os == 'macos-latest'
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          CSC_NAME: ${{ steps.signing.outputs.signing_identity }}
          APPLE_TEAM_ID: ${{ steps.signing.outputs.team_id }}
          PYTHON: python3.11
        run: node scripts/build.mjs buddy:mac

      # - name: build-win
      #   if: matrix.os == 'windows-latest'
      #   run: cd buddy && pnpm run build:win

      - name: release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'macos-latest'
        with:
          draft: true
          prerelease: true
          files: |
            buddy/dist/*.exe
            buddy/dist/*.zip
            buddy/dist/*.dmg
            buddy/dist/*.AppImage
            buddy/dist/*.snap
            buddy/dist/*.deb
            buddy/dist/*.rpm
            buddy/dist/*.tar.gz
            buddy/dist/*.yml
            buddy/dist/*.blockmap
